services:
  - type: web
    name: flowise
    env: node
    repo: https://github.com/FlowiseAI/Flowise.git
    buildCommand: npm install
    startCommand: npx flowise start
    plan: free
    envVars:
      - key: PORT
        value: 3000
